//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC_AjudaMutuaSLZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public Clientes()
        {
            this.Arquivo = new HashSet<Arquivo>();
            this.Comprovante = new HashSet<Comprovante>();
            this.Rede = new HashSet<Rede>();
            this.UpLine = new HashSet<UpLine>();
        }
    
        public int idCliente { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Telefone { get; set; }
        public string SKYPE { get; set; }
        public string Senha { get; set; }
        public string Banco { get; set; }
        public string TipoConta { get; set; }
        public string Agencia { get; set; }
        public string Conta { get; set; }
        public string Operacao { get; set; }
        public string Patrocinador { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<Arquivo> Arquivo { get; set; }
        public virtual ICollection<Comprovante> Comprovante { get; set; }
        public virtual ICollection<Rede> Rede { get; set; }
        public virtual ICollection<UpLine> UpLine { get; set; }
    }
}
