//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JC_AjudaMutuaSLZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpLine
    {
        public int idUpLine { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idOrigem { get; set; }
        public Nullable<int> Posicao { get; set; }
        public string Status { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
